#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
API_DIR="$ROOT_DIR/apps/api"
VENV_DIR="$API_DIR/.venv"
GPU_ENV_FILE="$API_DIR/.gpu-env"

# ─── Detection helpers ───────────────────────────────────────────────────────

detect_wsl() {
    grep -qi microsoft /proc/version 2>/dev/null && echo "true" || echo "false"
}

detect_ubuntu_codename() {
    local codename
    codename=$(. /etc/os-release && echo "$VERSION_CODENAME")
    case "$codename" in
        jammy|noble) echo "$codename" ;;
        *)
            echo -e "${YELLOW}Warning: Unknown Ubuntu codename '$codename', assuming noble${NC}" >&2
            echo "noble"
            ;;
    esac
}

detect_gpu() {
    local gpu_info=""

    # WSL2: query the Windows host via PowerShell
    if [ "$IS_WSL" = "true" ]; then
        gpu_info=$(powershell.exe -NoProfile -Command \
            "Get-CimInstance Win32_VideoController | Select-Object -ExpandProperty Name" 2>/dev/null | tr -d '\r' || true)
    fi

    # Native Linux or fallback: use lspci
    if [ -z "$gpu_info" ] && command -v lspci &>/dev/null; then
        gpu_info=$(lspci 2>/dev/null | grep -iE 'VGA|3D|Display' || true)
    fi

    # Device node fallbacks
    if [ -z "$gpu_info" ]; then
        if [ -e /dev/kfd ] || [ -e /dev/dxg ]; then
            echo "amd"
            return
        fi
        if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
            echo "nvidia"
            return
        fi
        echo "none"
        return
    fi

    # Parse the info string — check NVIDIA first (more specific), then AMD/Radeon
    if echo "$gpu_info" | grep -qi nvidia; then
        echo "nvidia"
    elif echo "$gpu_info" | grep -qiE 'AMD|Radeon'; then
        echo "amd"
    else
        echo "none"
    fi
}

# ─── ROCm install (AMD only) ────────────────────────────────────────────────

install_rocm() {
    if [ -x /opt/rocm/bin/rocminfo ]; then
        local rocm_ver
        rocm_ver=$(/opt/rocm/bin/rocminfo 2>/dev/null | head -1 || true)
        echo -e "${GREEN}ROCm already installed${NC}"
        /opt/rocm/bin/rocminfo 2>/dev/null | grep -E "Name:.*gfx" | head -1 || true
        return
    fi

    echo -e "${YELLOW}Installing ROCm 7.2...${NC}"

    local codename
    codename=$(detect_ubuntu_codename)
    local deb_url="https://repo.radeon.com/amdgpu-install/7.2/ubuntu/${codename}/amdgpu-install_7.2.70200-1_all.deb"
    local deb_path="/tmp/amdgpu-install_7.2.70200-1_all.deb"

    echo "Downloading ROCm installer for Ubuntu $codename..."
    wget -q --show-progress -O "$deb_path" "$deb_url"

    echo "Installing amdgpu-install package..."
    sudo apt install -y "$deb_path"

    if [ "$IS_WSL" = "true" ]; then
        echo -e "${CYAN}WSL2 detected — installing with wsl,rocm usecase${NC}"
        sudo amdgpu-install -y --usecase=wsl,rocm --no-dkms
    else
        echo "Installing ROCm for native Linux..."
        sudo amdgpu-install -y --usecase=rocm --no-dkms
    fi

    # Add user to render/video groups
    sudo usermod -a -G render,video "$USER" 2>/dev/null || true

    echo -e "${GREEN}ROCm installed.${NC}"

    if [ "$IS_WSL" = "true" ]; then
        echo -e "${YELLOW}Note: AMD Adrenalin 26.1.1+ driver must be installed on the Windows host.${NC}"
    fi
}

# ─── PyTorch install ─────────────────────────────────────────────────────────

install_pytorch() {
    local gpu="$1"

    echo -e "${YELLOW}Installing PyTorch for: ${CYAN}${gpu}${NC}"

    case "$gpu" in
        amd)
            pip install torch torchvision --index-url https://download.pytorch.org/whl/rocm7.1
            ;;
        nvidia)
            pip install torch torchvision
            ;;
        none)
            pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
            ;;
    esac
}

# ─── Write .gpu-env ──────────────────────────────────────────────────────────

write_gpu_env() {
    local gpu="$1"

    echo -e "${YELLOW}Writing GPU environment to ${GPU_ENV_FILE}${NC}"

    cat > "$GPU_ENV_FILE" <<EOF
# Auto-generated by setup-gpu.sh — DO NOT EDIT MANUALLY
# Generated: $(date -Iseconds)
# GPU: ${gpu}
EOF

    case "$gpu" in
        amd)
            cat >> "$GPU_ENV_FILE" <<'EOF'

export GPU_VENDOR=amd
export LD_PRELOAD=/opt/rocm/lib/libamdhip64.so
export HSA_OVERRIDE_GFX_VERSION=11.0.0
export HSA_ENABLE_SDMA=0
export LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export PATH=${PATH:+$PATH:}/opt/rocm/bin
EOF
            ;;
        nvidia)
            cat >> "$GPU_ENV_FILE" <<'EOF'

export GPU_VENDOR=nvidia
EOF
            ;;
        none)
            cat >> "$GPU_ENV_FILE" <<'EOF'

export GPU_VENDOR=none
EOF
            ;;
    esac
}

# ─── Update ~/.bashrc (AMD only) ─────────────────────────────────────────────

update_bashrc() {
    local marker="# >>> auto-gamer gpu-env >>>"
    if grep -qF "$marker" ~/.bashrc 2>/dev/null; then
        echo "~/.bashrc already has gpu-env source line"
        return
    fi

    echo "Adding gpu-env to ~/.bashrc..."
    cat >> ~/.bashrc <<EOF

${marker}
[ -f "$GPU_ENV_FILE" ] && source "$GPU_ENV_FILE"
# <<< auto-gamer gpu-env <<<
EOF
}

# ─── Verify ──────────────────────────────────────────────────────────────────

verify_pytorch() {
    local gpu="$1"
    echo ""
    echo -e "${YELLOW}Verifying PyTorch installation...${NC}"

    # Source gpu-env so LD_PRELOAD is active for AMD
    if [ -f "$GPU_ENV_FILE" ]; then
        source "$GPU_ENV_FILE"
    fi

    python -c "
import torch
ver = torch.__version__
avail = torch.cuda.is_available()
count = torch.cuda.device_count()
print(f'  PyTorch:        {ver}')
print(f'  CUDA/ROCm:      {avail}')
print(f'  Device count:   {count}')
if avail and count > 0:
    print(f'  GPU:            {torch.cuda.get_device_name(0)}')
    print(f'  VRAM:           {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB')
"

    if [ "$gpu" != "none" ]; then
        local avail
        avail=$(python -c "import torch; print(torch.cuda.is_available())")
        if [ "$avail" = "True" ]; then
            echo -e "  ${GREEN}GPU acceleration is working.${NC}"
        else
            echo -e "  ${RED}Warning: GPU not detected by PyTorch.${NC}"
            if [ "$gpu" = "amd" ]; then
                echo -e "  ${YELLOW}For AMD: ensure LD_PRELOAD is set. Try: source ~/.bashrc${NC}"
            fi
        fi
    else
        echo -e "  ${CYAN}Running in CPU-only mode.${NC}"
    fi
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    echo ""
    echo -e "${CYAN}=== GPU Setup ===${NC}"
    echo ""

    # Ensure venv is active
    if [ -z "$VIRTUAL_ENV" ]; then
        if [ -f "$VENV_DIR/bin/activate" ]; then
            source "$VENV_DIR/bin/activate"
        else
            echo -e "${RED}Error: No virtual environment found at $VENV_DIR${NC}"
            echo "Run setup-python.sh first or activate your venv."
            exit 1
        fi
    fi

    # Detect environment
    IS_WSL=$(detect_wsl)
    local gpu
    gpu=$(detect_gpu)

    echo -e "  Environment:  $([ "$IS_WSL" = "true" ] && echo "WSL2" || echo "Native Linux")"
    echo -e "  GPU detected: ${CYAN}${gpu}${NC}"
    echo ""

    # Install GPU runtime + PyTorch
    case "$gpu" in
        amd)
            install_rocm
            echo ""
            install_pytorch amd
            write_gpu_env amd
            update_bashrc
            ;;
        nvidia)
            install_pytorch nvidia
            write_gpu_env nvidia
            ;;
        none)
            install_pytorch none
            write_gpu_env none
            ;;
    esac

    verify_pytorch "$gpu"

    echo ""
    echo -e "${GREEN}=== GPU Setup Complete ===${NC}"
    echo ""
}

main "$@"
